In [1]:
import sys
from pathlib import Path

project_root = Path.cwd().parent if Path.cwd().name == "notebooks" else Path.cwd()
sys.path.insert(0, str(project_root))

from src.preprocessing import load_player_data, preprocess_player_data

print("Import fungsi preprocessing berhasil.")

Import fungsi preprocessing berhasil.

In [2]:
df = load_player_data()
df_pencarian = preprocess_player_data(df)

print("Jumlah data awal:", len(df))
print("Jumlah data siap pencarian:", len(df_pencarian))
print("Jumlah kolom hasil:", len(df_pencarian.columns))

display(df_pencarian.head())

Jumlah data awal: 92671
Jumlah data siap pencarian: 92151
Jumlah kolom hasil: 9

,player_id,player_name,main_position,position,current_club_name,citizenship,foot,height,age
0,1,Silvio Adzic (1),Attack,Attack - Right Winger,Retired,Germany,NaN,NaN,46.0
1,100011,Éverton Silva (100011),Defender,Defender - Right-Back,Without Club,Brazil,right,171.0,38.0
2,10,Miroslav Klose (10),Attack,Attack - Centre-Forward,Retired,Germany,right,184.0,48.0
3,10001,John Thompson (10001),Defender,Defender - Right-Back,Retired,Ireland,both,183.0,45.0
4,100001,Carlos Auzqui (100001),Attack,Attack - Right Winger,Club Atlético Tucumán,Argentina,right,180.0,35.0

In [3]:

from src.recommender import PlayerRecommender

model = PlayerRecommender(df_pencarian)

print("Model rekomendasi berhasil dibuat.")
print("Ukuran matriks TF-IDF:", model.tfidf_matrix.shape)

Model rekomendasi berhasil dibuat.
Ukuran matriks TF-IDF: (92151, 13564)

In [4]:

hasil_cari = model.search_players("Silvio", 10)

print("Jumlah kandidat:", len(hasil_cari))
display(hasil_cari)

Jumlah kandidat: 10

,player_id,player_name,main_position,position,current_club_name,age,height
0,1,Silvio Adzic (1),Attack,Attack - Right Winger,Retired,46.0,NaN
12095,1310489,Silvio Cambrini (1310489),Midfield,Midfield - Attacking Midfield,Napoli Under 18,18.0,NaN
14389,1159,Silvio Schröter (1159),Midfield,Midfield - Right Midfield,Retired,47.0,180.0
18675,150,Silvio Meißner (150),Midfield,Midfield - Defensive Midfield,Retired,53.0,NaN
23686,174957,Silvio (174957),Goalkeeper,Goalkeeper,Retired,38.0,196.0
26800,20197,Silvio Enrique (20197),Midfield,Midfield,Retired,47.0,169.0
26811,202076,Silvio (202076),Defender,Defender - Centre-Back,Clube Náutico Marcílio Dias (SC),38.0,180.0
36777,317123,Silvio Vertullo (317123),Defender,Defender,Retired,46.0,NaN
38421,33545,Silvio Bär (33545),Defender,Defender - Centre-Back,Retired,43.0,NaN
40166,309593,Silvio Giusti (309593),Midfield,Midfield - Central Midfield,Retired,58.0,180.0

In [5]:

hasil_rekomendasi = model.recommend_by_id(1, 5)

if hasil_rekomendasi is None:
    print("Pemain tidak ditemukan.")
else:
    display(hasil_rekomendasi)

,player_id,player_name,main_position,position,current_club_name,age,height,similarity_score
0,1080,Albert Streit (1080),Attack,Attack - Right Winger,Retired,46.0,NaN,1.000000
1,1558,Steffen Handschuh (1558),Attack,Attack - Centre-Forward,Retired,46.0,NaN,0.838304
2,2081,Holm Hentschke (2081),Attack,Attack - Centre-Forward,Retired,46.0,NaN,0.838304
3,8364,Andreas Gerdes-Wurpts (8364),Attack,Attack - Centre-Forward,Retired,46.0,NaN,0.838304
4,67,Markus Daun (67),Attack,Attack - Centre-Forward,Retired,46.0,185.0,0.787212

In [6]:

hasil_tidak_ditemukan = model.recommend_by_id(999999999, 5)

if hasil_tidak_ditemukan is None:
    print("Pemain dengan ID 999999999 tidak ditemukan.")
else:
    display(hasil_tidak_ditemukan)

Pemain dengan ID 999999999 tidak ditemukan.

In [7]:
model = PlayerRecommender(df_pencarian)

In [8]:
hasil_rekomendasi = model.recommend_by_id(1, 5)

if hasil_rekomendasi is None:
    print("Pemain tidak ditemukan.")
else:
    display(hasil_rekomendasi)

,player_id,player_name,main_position,position,current_club_name,age,height,similarity_score
0,1080,Albert Streit (1080),Attack,Attack - Right Winger,Retired,46.0,NaN,1.000000
1,1558,Steffen Handschuh (1558),Attack,Attack - Centre-Forward,Retired,46.0,NaN,0.838304
2,2081,Holm Hentschke (2081),Attack,Attack - Centre-Forward,Retired,46.0,NaN,0.838304
3,8364,Andreas Gerdes-Wurpts (8364),Attack,Attack - Centre-Forward,Retired,46.0,NaN,0.838304
4,67,Markus Daun (67),Attack,Attack - Centre-Forward,Retired,46.0,185.0,0.787212

In [9]:
display(
    df_pencarian.loc[
        df_pencarian["player_id"] == 1,
        ["player_id", "player_name", "main_position"]
    ]
)

   player_id       player_name main_position
0          1  Silvio Adzic (1)        Attack

In [10]:
from src.recommender import PlayerRecommender

model = PlayerRecommender(df_pencarian)

print(
    df_pencarian.loc[
        df_pencarian["player_id"] == 1,
        ["player_id", "player_name"]
    ]
)

   player_id       player_name
0          1  Silvio Adzic (1)

In [11]:
display(model.recommend_by_id(1, 5))

,player_id,player_name,main_position,position,current_club_name,age,height,similarity_score
0,1080,Albert Streit (1080),Attack,Attack - Right Winger,Retired,46.0,NaN,1.000000
1,1558,Steffen Handschuh (1558),Attack,Attack - Centre-Forward,Retired,46.0,NaN,0.838304
2,2081,Holm Hentschke (2081),Attack,Attack - Centre-Forward,Retired,46.0,NaN,0.838304
3,8364,Andreas Gerdes-Wurpts (8364),Attack,Attack - Centre-Forward,Retired,46.0,NaN,0.838304
4,67,Markus Daun (67),Attack,Attack - Centre-Forward,Retired,46.0,185.0,0.787212

In [12]:
import inspect
print(inspect.getsource(PlayerRecommender.recommend_by_id))

    def search_players(self, nama_pemain, batas_hasil=10):
        """Mencari pemain berdasarkan sebagian nama."""

        hasil = self.df[
            self.df["player_name"].str.contains(
                nama_pemain,
                case=False,
                na=False,
                regex=False
            )
        ]

        kolom_tampilan = [
            "player_id",
            "player_name",
            "main_position",
            "position",
            "current_club_name",
            "age",
            "height"
        ]

        return hasil[kolom_tampilan].head(batas_hasil).copy()

In [14]:
from importlib import reload
import src.recommender as recommender_module

reload(recommender_module)

PlayerRecommender = recommender_module.PlayerRecommender
model = PlayerRecommender(df_pencarian)

display(model.recommend_by_id(1, 5))

,player_id,player_name,main_position,position,current_club_name,age,height,similarity_score
0,1080,Albert Streit (1080),Attack,Attack - Right Winger,Retired,46.0,NaN,1.000000
1,8364,Andreas Gerdes-Wurpts (8364),Attack,Attack - Centre-Forward,Retired,46.0,NaN,0.838304
2,1558,Steffen Handschuh (1558),Attack,Attack - Centre-Forward,Retired,46.0,NaN,0.838304
3,2081,Holm Hentschke (2081),Attack,Attack - Centre-Forward,Retired,46.0,NaN,0.838304
4,67,Markus Daun (67),Attack,Attack - Centre-Forward,Retired,46.0,185.0,0.787212

In [15]:
print("Pemain target:")
display(
    model.df.loc[
        model.df["player_id"] == 1,
        ["player_id", "player_name", "profile_text"]
    ]
)

print("Profil Albert Streit:")
display(
    model.df.loc[
        model.df["player_id"] == 1080,
        ["player_id", "player_name", "profile_text"]
    ]
)

Pemain target:

,player_id,player_name,profile_text
0,1,Silvio Adzic (1),Attack Attack - Right Winger Retired Germany a...

Profil Albert Streit:

,player_id,player_name,profile_text
6826,1080,Albert Streit (1080),Attack Attack - Right Winger Retired Germany a...

In [16]:
silvio = model.df.loc[
    model.df["player_id"] == 1, "profile_text"
].iloc[0]

albert = model.df.loc[
    model.df["player_id"] == 1080, "profile_text"
].iloc[0]

print("Profil Silvio Adzic:")
print(silvio)

print("\nProfil Albert Streit:")
print(albert)

print("\nApakah profilnya identik?", silvio == albert)

Profil Silvio Adzic:
Attack Attack - Right Winger Retired Germany age_46

Profil Albert Streit:
Attack Attack - Right Winger Retired Germany age_46

Apakah profilnya identik? True

In [17]:
from sklearn.metrics.pairwise import cosine_similarity

idx_silvio = model.df.index[
    model.df["player_id"] == 1
][0]

idx_albert = model.df.index[
    model.df["player_id"] == 1080
][0]

skor = cosine_similarity(
    model.tfidf_matrix[idx_silvio],
    model.tfidf_matrix[idx_albert]
)[0, 0]

print("Skor kemiripan Silvio dan Albert:", round(skor, 6))

Skor kemiripan Silvio dan Albert: 1.0

In [18]:
print("Daftar kolom dataset:")
print(df.columns.tolist())

Daftar kolom dataset:
['player_id', 'player_slug', 'player_name', 'player_image_url', 'name_in_home_country', 'date_of_birth', 'place_of_birth', 'country_of_birth', 'height', 'citizenship', 'is_eu', 'position', 'main_position', 'foot', 'current_club_id', 'current_club_name', 'joined', 'contract_expires', 'outfitter', 'social_media_url', 'player_agent_id', 'player_agent_name', 'contract_option', 'date_of_last_contract_extension', 'on_loan_from_club_id', 'on_loan_from_club_name', 'contract_there_expires', 'second_club_url', 'second_club_name', 'third_club_url', 'third_club_name', 'fourth_club_url', 'fourth_club_name', 'date_of_death']

In [19]:

kolom_tambahan = [
    "country_of_birth",
    "place_of_birth",
    "outfitter",
    "current_club_name",
    "foot",
    "height",
    "date_of_birth"
]

for kolom in kolom_tambahan:
    jumlah_isi = df[kolom].notna().sum()
    persentase = round(jumlah_isi / len(df) * 100, 2)

    print(
        f"{kolom}: {jumlah_isi:,} data terisi "
        f"({persentase}%)"
    )

country_of_birth: 76,026 data terisi (82.04%)
place_of_birth: 76,038 data terisi (82.05%)
outfitter: 5,958 data terisi (6.43%)
current_club_name: 92,671 data terisi (100.0%)
foot: 69,183 data terisi (74.65%)
height: 92,667 data terisi (100.0%)
date_of_birth: 91,665 data terisi (98.91%)

In [21]:
from importlib import reload
import src.preprocessing as preprocessing_module

reload(preprocessing_module)

df = preprocessing_module.load_player_data()
df_pencarian = preprocessing_module.preprocess_player_data(df)

print(df_pencarian.columns.tolist())

['player_id', 'player_name', 'main_position', 'position', 'current_club_name', 'citizenship', 'country_of_birth', 'place_of_birth', 'foot', 'height', 'age']

In [22]:
from importlib import reload
import src.recommender as recommender_module

reload(recommender_module)

PlayerRecommender = recommender_module.PlayerRecommender
model = PlayerRecommender(df_pencarian)

print("Model rekomendasi berhasil dibuat.")
print("Ukuran matriks TF-IDF:", model.tfidf_matrix.shape)

display(model.recommend_by_id(1, 5))

Model rekomendasi berhasil dibuat.
Ukuran matriks TF-IDF: (92151, 269)

,player_id,player_name,main_position,position,current_club_name,age,height,similarity_score
0,1080,Albert Streit (1080),Attack,Attack - Right Winger,Retired,46.0,NaN,1.000000
1,432673,Dominic Fuß (432673),Attack,Attack - Right Winger,SG 2000 Mülheim-Kärlich,<NA>,NaN,1.000000
2,51,Christian Timm (51),Attack,Attack - Right Winger,Retired,47.0,NaN,0.990196
3,43822,Toni Lindenhahn (43822),Attack,Attack - Right Winger,Retired,<NA>,175.0,0.988608
4,58030,Christoph Hemlein (58030),Attack,Attack - Right Winger,Retired,<NA>,181.0,0.988608

In [23]:
hasil_cari = model.search_players("Silvio", 10)

print("Jumlah kandidat:", len(hasil_cari))
display(hasil_cari)

Jumlah kandidat: 10

,player_id,player_name,main_position,position,current_club_name,age,height
0,1,Silvio Adzic (1),Attack,Attack - Right Winger,Retired,46.0,NaN
12095,1310489,Silvio Cambrini (1310489),Midfield,Midfield - Attacking Midfield,Napoli Under 18,18.0,NaN
14389,1159,Silvio Schröter (1159),Midfield,Midfield - Right Midfield,Retired,47.0,180.0
18675,150,Silvio Meißner (150),Midfield,Midfield - Defensive Midfield,Retired,53.0,NaN
23686,174957,Silvio (174957),Goalkeeper,Goalkeeper,Retired,38.0,196.0
26800,20197,Silvio Enrique (20197),Midfield,Midfield,Retired,47.0,169.0
26811,202076,Silvio (202076),Defender,Defender - Centre-Back,Clube Náutico Marcílio Dias (SC),38.0,180.0
36777,317123,Silvio Vertullo (317123),Defender,Defender,Retired,46.0,NaN
38421,33545,Silvio Bär (33545),Defender,Defender - Centre-Back,Retired,43.0,NaN
40166,309593,Silvio Giusti (309593),Midfield,Midfield - Central Midfield,Retired,58.0,180.0